packages:
  - student-app
  - academy-app
  - backend/api
  - backend/shared/*
allowBuilds:
  '@biomejs/biome': true
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
